### ISSUE TITLE
Flutter button working

### ISSUE THREAD

**Issue by Shree-77** [Shree-77/TicTacToe#1]
The first touch does nothing. I need this work from my first tap on the boxes

**Comment by Rahul0714** [comment]
Can I work on this issue?

**Comment by Rahul0714** [comment]
void handleMove(int index) {
    setState(() {
      //print(currentPlayer);
      game[index] = currentPlayer;
      if (currentPlayer == player1) {
        currentPlayer = player2;
      } else {
        currentPlayer = player1;
      }
    });
  }
The issue was currentPlayer was empty every first time and it was getting updated with either player1 or player2 on the second tap, so a solution would be to assign currentPlayer with player1 or player2. Assuming player1 will start the game I've assigned currentPlayer to player1.

**Comment by Shree-77** [comment]
Sure and thanks.
